---
title: "Report of the training course in R environment"
author: "Bjarki Þór Elvarsson and Einar Hjörleisson"
output: html_document
---

# Summary


# Background
___

## Context

The R language is becoming the _Lingua franca_ both in data science in general as well as within the ICES community. Recent advancements within R have resulted in that R can no longer be considered as a specific statistical programming language but as a general scientific working environment. This broader environment has resulted in the R has become a natural component of reproducible data analysis and document writing.

Various R packages (e.g. FLR, DATRAS, MSY, SURBAR, VMStools) have often been the backbone of ICES training course and/or workshops. These packages as well as courses are geared towards solving specific pending tasks that tend to come with requirements that the participants are reasonable proficient in basic R and that the input data are correctly formatted and available. Any of these requirements have been seen to pose problems.

The course is aimed at covering the fundamental/generic basis of the grammar of data and graphics as well reproducible document writing where R is used as the sole working medium. Recent developments in the R community that are of interest to fisheries science will also be described.

## Objective

The objective of the course is to provide participants with a solid foundation in efficient use of the R environment using various typical and familiar fisheries data sets (landings data, catch data, survey data and tagging data) as case examples. Emphasis will be put on data munging and literate programming starting with "raw" data (individual stations, individual fish measurements) and culminating with deliverance of publishable output produced from a single coded document file.

By the end of the course, the participants:

  * Will be able to import data from multitude of sources computer (i.e. own text files, excel, access, sql databases) and via the web.
  * Will be able to clean, manipulate, explore, summarize and graph data. This includes being able to:
      - Apply best practices in data preparation
      - Present results graphically, highlighting significant results
      - Merge, slice and dice various datasets
  * Will be able to apply the principle of reproducible analysis and report writing from A through Z which are then deliverable through any of the current three common deliverable formats: .html, .pdf and .docx.
  * Will be able to produce own functions and understand the principles of creating R packages as well participate in social coding (through www.github.com).

## Level

The course is targeted at fisheries scientist with already have some basic experience in R but are yet not proficient enough to write fluently code for data manipulation, exploration and writing own functions. We believe that some part of the course would also be beneficial to those that are currently productively using R in fisheries science but may along the way have skipped the basics or are unaware of recent advancements in the R environment.

# Course Programme, Product, Deliverance and Instructors

## Programme

The schedule as set up prior to the course was as follows:

### Day 1 - Monday

* Introduction:
    - Rstudio and R projects
    - knitr, markdown, document writing (html, pdf,  docx)
    - reproducible analysis using R
* Getting data into R and out of R:
    - from ones own computer (text files, excel, ...)
    - from the web
    - from API's (ICES Webservices)
    - from databases (Ram's online Postgres database)
* The grammar of data and graphics:
    - Introduction to ggplot2
    - Introduction to dplyr

### Day 2 - Tuesday

* The grammar of data and graphics - continued:
    - Exploratory data analysis and visualization
* Working with characters and dates
* The base R equivalence

### Day 3 - Wednesday

* GIS in R
    - using ggplot2 and ggmap
    - using leaflet
* Applied project(s) - From "messy" data to a final report using reproducible approach based on case examples
    - candidate: abundance and biomass indices starting with ICES DATRAS data

### Day 4 - Thursday

* Applied project - continued

### Day 5 - Friday
* The fundamentals of functions and package writing
    - Fundamental of functions and documentation
    - Directory structure and a minimal example
    - Version control (git) and social coding (www.github.com)

## Course products

From the conception of the course through deliverance, all course material were developed and delivered using non-propriory free software. In that spirit all the material was also made available as open source. To that end a github repository was generated (https://github.com/fishvice/tcrenv2016) that contains all source documents (in the form of .Rmd and/or .Rnw) and data, with associated output documents (.html and/or .pdf format). A webpage (http://www.hafro.is/~einarhj/education/tcrenv2016/) based on that material was also generated and used throughout the course.

The above product allows anybody interest to make a full copy of the course, either as a compiled zip-document (https://github.com/fishvice/tcrenv2016/archive/master.zip) or by simply typing in a terminal window on computers where the git program has been installed:
```
git clone https://github.com/fishvice/tcrenv2016.git
```

During the development of the course, the ICES secretariat asked the instructors to consider the usage of the BlueBridge Virtual Research Environment (BVRE) as a platform for the course. BVRE is all encompassing environment for collaborative work such as projects in a university course. Projects can import powerful modules or tools that allow a particular analysis. Similarly data can be imported through a set of fixed data import routines and made available to the projects participants. The BVRE is accessed through a browser and all the analysis is made on centralised servers. This approach therefore makes very little demands on the computer platform of the end user or available software, all that is required is a modern browser and a stable internet connection. Very superficial exploration was made with respect to the usefulness of this platform and it was concluded that it most likely would not be any better than the approach as described above. Although BVRE has an impressive feature it requires an additional investment and would add layer of confusion for the course participants. Although R is a available from within BVRE, its use is somewhat restricted. Notably it is assumed that most of the data handling is done through BVRE. In contrast, the course covered various ways of working with data with R from multiple sources. Additionally the benefit for the user is not obvious as the course participants are not likely to have access to the BRVE at their home institutions.  


## Deliverables

The major change from the planned schedule described above and the actual course deliverance was that the coverage of each topic, including practial assignments took longer than anticipated. This resulted in that the topics scheduled for Friday were more or less put on the back burner and were only covered with brief lectures without participants hands on training.

Each day was split up into group discussion of the topics/assignments covered the previous day, introduction lectures of the day's topics followed by practical assignments. Emphasis was put on cooperative work and code sharing (including difficulties/stumbling blocks) among participants. The practical assignments were fairly diverse, ranging from simple summary statistics based on DATRAS dat, to maps of fishing intensity and collating landing statistics. In addition course participants were encouraged to work with their own data and problems using R. These included time series analysis of fish price, automatic cruise reports and biomass estimation of zoo plankton. 

## Lecturers

* Bjarki Þór Elvarsson, Marine Research Institute, Iceland
    - Bjarki is a statistician in the Fisheries Advisory Section of the Marine Research Institute, Reykjavík Iceland. He recently finished his phd in statistical methods related to stock assessment models. He has been a member of the Icelandic delegation to the scientific council of International whaling commission since 2010 and participated in various ICES working group meetings since 2013. R has been in his main working environment since 2004. 
* Einar Hjörleifsson, Marine Research Institute, Iceland
    - Einar is a fisheries scientist in Fisheries Advisory Section of the Marine Research Institute, Reykjavík Iceland. He has been involved in various ICES works since 1996 that spans the whole spectrum from ACFM/ACOM membership up to working group participation. In the early 2000's he taught stock assessment at ICES with Dankert Skagen for three consequtive years. He has also been involved in the United Nation University Fisheries Training Program teaching stock assessment. R has been his primary working environment since 2009.

# Recommendation

In the waining hour of the course a discussion focusing on what may have been handeled better by the instructors. The main comments were:

* Document organization
    - Documents and data were distributed by the instructors in any of three different spaces (web-access, sharepoint, github). It was recommended that if the course is tought again all material distributed via only one space. It should also be considered if course content could not be organized by the day covered.
* Order and scope of the course material:
    - Data importing, checking, tidying and "mining" should be put upfront in the course.
    - Question was raised if the usage of R-package development and version control (git) was outside the main scope of the course. If the course were to be trimmed the R-package development was considered to be the most obvious canditate to put on the chopping block. If version control was to be retained as a part of the course content, it was suggested that it is thought as a part of the assignments.


# Annex 1: List of participants

# Annex 2: Results of course evaluation questionnaire


